// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkiraytxspukxhkwzltx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdraXJheXR4c3B1a3hoa3d6bHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODc2MzMsImV4cCI6MjA2MTk2MzYzM30.tJ6_KUnIezDQ9k_U42lFpO6LSomTK8-60EObI5DHhkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);